services:
  postgresql:
    image: localhost/postgresql-ubi:development
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password
    ports:
      - "127.0.0.1:5432:5432"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,mode=1777
    volumes:
      - postgres-data:/var/lib/pgsql
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_signal: SIGINT

secrets:
  postgres-password:
    environment: POSTGRES_PASSWORD

volumes:
  postgres-data:
